
ALTER TABLE offers
  ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'available',
  ADD COLUMN IF NOT EXISTS sold_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS buyer_id INTEGER DEFAULT NULL REFERENCES users(id);

ALTER TABLE bids
  ADD COLUMN IF NOT EXISTS accepted BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  payload JSONB NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
